### ISSUE TITLE
Bottom page spacing

### ISSUE THREAD

**Issue by simoneb** [nearform/osscheck#103] opened 2023-09-07 14:16 UTC
Let's have some spacing at the bottom
![image](https://github.com/nearform/osscheck/assets/20181/672224f2-d950-4980-bc70-8da567782db7)

**Comment by travis-spanu-nearform** [comment] 2023-09-08 15:58
Duplicate of https://github.com/nearform/osscheck/issues/102

**Closed** 2023-09-20 09:33 UTC
